### ISSUE TITLE
TypeError thrown when heredoc defined incorrectly with <<< instead of <<

### ISSUE THREAD

**Issue by rcjsuen** [rcjsuen/dockerfile-ast#117]
```TypeScript
import { DockerfileParser, Run } from 'dockerfile-ast';
const content = "RUN <<<test\ntest\n";
const dockerfile = DockerfileParser.parse(content);
const run = dockerfile.getInstructions()[0] as Run;
run.getHeredocs();
```
```
./node_modules/dockerfile-ast/lib/instruction.js:842
            const startRange = arg.getRange();
                                   ^

TypeError: Cannot read properties of undefined (reading 'getRange')
    at Run.getHeredocs (./node_modules/dockerfile-ast/lib/instruction.js:842:36)
    at Run.getHeredocs (./node_modules/dockerfile-ast/lib/instructions/run.js:19:22)
    at Object.<anonymous> (./out/src/main.js:7:5)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.16.0
```

**Comment by Heptazhou** [comment]
Just FYI, a `<<<` is a here-string, not an invalid here-document (I believe that would be `<<)`, `<<>`, etc.).

Currently vscode syntax highlighting for dockerfile is broken after any here-string preceded by whitespace character,
and I find this problem is already fixed here, so I hope the fix will be in vscode-docker soon.

**Comment by rcjsuen** [comment]
> Currently vscode syntax highlighting for dockerfile is broken after any here-string preceded by whitespace character

Hi @Heptazhou, could you share a simple Dockerfile that uses `<<<` so I can see the behaviour on my machine? Thanks!
